export const crumbsList = [
  { name: "home", title: "首页" },
  { name: "courseCenter", title: "课程实验中心" },
  { name: "courseItem", title: "课程项目" },
  { name: "experimentalEnvironment", title: "实验环境" },
  { name: "steps1", title: "背景介绍" },
  { name: "steps2", title: "合同签订流程1-1" },
  { name: "steps3", title: "合同签订流程1-2" },
  { name: "steps4", title: "申请开证流程" },
  { name: "steps5", title: "传递信用证流程1-1" },
  { name: "steps6", title: "传递信用证流程1-2" },
  { name: "steps7", title: "发货提单流程" },
  { name: "steps8", title: "交单垫付流程1-1" },
  { name: "steps9", title: "交单垫付流程1-2" },
  { name: "steps10", title: "寄票偿付流程" },
  { name: "steps11", title: "赎单付款流程" },
  { name: "steps12", title: "提货交割流程1-1" },
  { name: "steps13", title: "提货交割流程1-2" },
  { name: "steps14", title: "核验货物流程" },
  { name: "steps15", title: "贸易完成流程" },
];
